name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for opening an issue!'
        pr-message: 'Congrats on your first pull request! If your file names follow the correct format and includes new code, a maintainer will go ahead and approve!'
